# Based on https://github.com/tlambert03/napari/blob/master/.github/workflows/make_bundle.yml
on:
  pull_request:
  release:
    types:
      - created

name: Create Windows Installer

jobs:
  build:
    name: Windows installer
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.9
      - name: Install yarg
        shell: bash -l {0}
        run: |
          python -m pip install yarg
      - name: Run script
        shell: bash -l {0}
        run: |
          python installers/Windows/installer.py 3.7.9 64 setup.py spyder.app.start:main spyder img_src/spyder.ico LICENSE.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          path: dist/Spyder_64bit.exe
          name: Spyder_64bit.exe
      - name: Get Release
        if: ${{github.event_name == 'release'}}
        id: get_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        uses: bruceadams/get-release@v1.2.0
      - name: Upload Release Asset
        if: ${{github.event_name == 'release'}}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: dist/Spyder_64bit.exe
          asset_name: Spyder_64bit.exe
          asset_content_type: application/vnd.microsoft.portable-executable